name: Docker Image CD

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code on runner
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t lazyanalyst/continuous_php_image
