name: Docker Image CD

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code on runner
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1

    - name: Login to ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r6d3k2f6

    - name: Build, tag and push the Docker image
      run: |
        docker build . -t lazyanalyst/continuous_php_image
        docker tag lazyanalyst/continuous_php_image:latest public.ecr.aws/r6d3k2f6/lazyanalyst/continuous_php_image:latest
        ocker push public.ecr.aws/r6d3k2f6/lazyanalyst/continuous_php_image:latest
